package net.keama.workspace.entity;
// Generated Feb 4, 2017 1:33:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CourrierResponsable generated by hbm2java
 */
@Entity
@Table(name="courrier_responsable"
    ,catalog="workspace"
)
public class CourrierResponsable  implements java.io.Serializable {


     private Integer idcourrierResponsable;
     private Courrier courrier;
     private CourrierProcedureEnCours courrierProcedureEnCours;
     private CourrierProcedureTache courrierProcedureTache;
     private Employe employe;
     private String statutPrecedent;
     private String statut;
     private Date dateRecuperation;
     private Date dateLimite;
     private String typeApprobation;
     private String commentaire;
     private Boolean needFile;
     private String libelle;
     private Set<CourrierResponsableCommentaire> courrierResponsableCommentaires = new HashSet<CourrierResponsableCommentaire>(0);

    public CourrierResponsable() {
    }

    public CourrierResponsable(Courrier courrier, CourrierProcedureEnCours courrierProcedureEnCours, CourrierProcedureTache courrierProcedureTache, Employe employe, String statutPrecedent, String statut, Date dateRecuperation, Date dateLimite, String typeApprobation, String commentaire, Boolean needFile, String libelle, Set<CourrierResponsableCommentaire> courrierResponsableCommentaires) {
       this.courrier = courrier;
       this.courrierProcedureEnCours = courrierProcedureEnCours;
       this.courrierProcedureTache = courrierProcedureTache;
       this.employe = employe;
       this.statutPrecedent = statutPrecedent;
       this.statut = statut;
       this.dateRecuperation = dateRecuperation;
       this.dateLimite = dateLimite;
       this.typeApprobation = typeApprobation;
       this.commentaire = commentaire;
       this.needFile = needFile;
       this.libelle = libelle;
       this.courrierResponsableCommentaires = courrierResponsableCommentaires;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcourrier_responsable", unique=true, nullable=false)
    public Integer getIdcourrierResponsable() {
        return this.idcourrierResponsable;
    }
    
    public void setIdcourrierResponsable(Integer idcourrierResponsable) {
        this.idcourrierResponsable = idcourrierResponsable;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcourrier")
    public Courrier getCourrier() {
        return this.courrier;
    }
    
    public void setCourrier(Courrier courrier) {
        this.courrier = courrier;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcourrier_procedure_en_cours")
    public CourrierProcedureEnCours getCourrierProcedureEnCours() {
        return this.courrierProcedureEnCours;
    }
    
    public void setCourrierProcedureEnCours(CourrierProcedureEnCours courrierProcedureEnCours) {
        this.courrierProcedureEnCours = courrierProcedureEnCours;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcourrier_procedure_tache")
    public CourrierProcedureTache getCourrierProcedureTache() {
        return this.courrierProcedureTache;
    }
    
    public void setCourrierProcedureTache(CourrierProcedureTache courrierProcedureTache) {
        this.courrierProcedureTache = courrierProcedureTache;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idresponsable")
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }

    
    @Column(name="statut_precedent", length=45)
    public String getStatutPrecedent() {
        return this.statutPrecedent;
    }
    
    public void setStatutPrecedent(String statutPrecedent) {
        this.statutPrecedent = statutPrecedent;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_recuperation", length=19)
    public Date getDateRecuperation() {
        return this.dateRecuperation;
    }
    
    public void setDateRecuperation(Date dateRecuperation) {
        this.dateRecuperation = dateRecuperation;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_limite", length=19)
    public Date getDateLimite() {
        return this.dateLimite;
    }
    
    public void setDateLimite(Date dateLimite) {
        this.dateLimite = dateLimite;
    }

    
    @Column(name="type_approbation", length=45)
    public String getTypeApprobation() {
        return this.typeApprobation;
    }
    
    public void setTypeApprobation(String typeApprobation) {
        this.typeApprobation = typeApprobation;
    }

    
    @Column(name="commentaire")
    public String getCommentaire() {
        return this.commentaire;
    }
    
    public void setCommentaire(String commentaire) {
        this.commentaire = commentaire;
    }

    
    @Column(name="need_file")
    public Boolean getNeedFile() {
        return this.needFile;
    }
    
    public void setNeedFile(Boolean needFile) {
        this.needFile = needFile;
    }

    
    @Column(name="libelle", length=45)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="courrierResponsable")
    public Set<CourrierResponsableCommentaire> getCourrierResponsableCommentaires() {
        return this.courrierResponsableCommentaires;
    }
    
    public void setCourrierResponsableCommentaires(Set<CourrierResponsableCommentaire> courrierResponsableCommentaires) {
        this.courrierResponsableCommentaires = courrierResponsableCommentaires;
    }




}


