package net.keama.workspace.entity;
// Generated Feb 4, 2017 1:33:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CourrierFichier generated by hbm2java
 */
@Entity
@Table(name="courrier_fichier"
    ,catalog="workspace"
)
public class CourrierFichier  implements java.io.Serializable {


     private Integer idcourrierFichier;
     private Courrier courrier;
     private String nom;
     private String chemin;
     private Date dateEnr;
     private String statut;
     private Integer ordre;

    public CourrierFichier() {
    }

    public CourrierFichier(Courrier courrier, String nom, String chemin, Date dateEnr, String statut, Integer ordre) {
       this.courrier = courrier;
       this.nom = nom;
       this.chemin = chemin;
       this.dateEnr = dateEnr;
       this.statut = statut;
       this.ordre = ordre;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcourrier_fichier", unique=true, nullable=false)
    public Integer getIdcourrierFichier() {
        return this.idcourrierFichier;
    }
    
    public void setIdcourrierFichier(Integer idcourrierFichier) {
        this.idcourrierFichier = idcourrierFichier;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcourier")
    public Courrier getCourrier() {
        return this.courrier;
    }
    
    public void setCourrier(Courrier courrier) {
        this.courrier = courrier;
    }

    
    @Column(name="nom", length=45)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="chemin", length=45)
    public String getChemin() {
        return this.chemin;
    }
    
    public void setChemin(String chemin) {
        this.chemin = chemin;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_enr", length=19)
    public Date getDateEnr() {
        return this.dateEnr;
    }
    
    public void setDateEnr(Date dateEnr) {
        this.dateEnr = dateEnr;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

    
    @Column(name="ordre")
    public Integer getOrdre() {
        return this.ordre;
    }
    
    public void setOrdre(Integer ordre) {
        this.ordre = ordre;
    }




}


