package net.keama.workspace.entity;
// Generated Feb 4, 2017 1:33:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Courrier generated by hbm2java
 */
@Entity
@Table(name="courrier"
    ,catalog="workspace"
    , uniqueConstraints = @UniqueConstraint(columnNames="ref") 
)
public class Courrier  implements java.io.Serializable {


     private Integer idcourrier;
     private Correspondant correspondant;
     private Structure structure;
     private String ref;
     private String expediteur;
     private String objet;
     private String adresseExpediteur;
     private Integer importance;
     private String support;
     private Date dateEmission;
     private Date dateEnr;
     private String note;
     private String statut;
     private String nature;
     private Boolean entrant;
     private Set<CourrierFichier> courrierFichiers = new HashSet<CourrierFichier>(0);
     private Set<CourrierResponsable> courrierResponsables = new HashSet<CourrierResponsable>(0);
     private Set<CourrierProcedureEnCours> courrierProcedureEnCourses = new HashSet<CourrierProcedureEnCours>(0);

    public Courrier() {
    }

    public Courrier(Correspondant correspondant, Structure structure, String ref, String expediteur, String objet, String adresseExpediteur, Integer importance, String support, Date dateEmission, Date dateEnr, String note, String statut, String nature, Boolean entrant, Set<CourrierFichier> courrierFichiers, Set<CourrierResponsable> courrierResponsables, Set<CourrierProcedureEnCours> courrierProcedureEnCourses) {
       this.correspondant = correspondant;
       this.structure = structure;
       this.ref = ref;
       this.expediteur = expediteur;
       this.objet = objet;
       this.adresseExpediteur = adresseExpediteur;
       this.importance = importance;
       this.support = support;
       this.dateEmission = dateEmission;
       this.dateEnr = dateEnr;
       this.note = note;
       this.statut = statut;
       this.nature = nature;
       this.entrant = entrant;
       this.courrierFichiers = courrierFichiers;
       this.courrierResponsables = courrierResponsables;
       this.courrierProcedureEnCourses = courrierProcedureEnCourses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcourrier", unique=true, nullable=false)
    public Integer getIdcourrier() {
        return this.idcourrier;
    }
    
    public void setIdcourrier(Integer idcourrier) {
        this.idcourrier = idcourrier;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcorrespondant")
    public Correspondant getCorrespondant() {
        return this.correspondant;
    }
    
    public void setCorrespondant(Correspondant correspondant) {
        this.correspondant = correspondant;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idservice")
    public Structure getStructure() {
        return this.structure;
    }
    
    public void setStructure(Structure structure) {
        this.structure = structure;
    }

    
    @Column(name="ref", unique=true, length=45)
    public String getRef() {
        return this.ref;
    }
    
    public void setRef(String ref) {
        this.ref = ref;
    }

    
    @Column(name="expediteur")
    public String getExpediteur() {
        return this.expediteur;
    }
    
    public void setExpediteur(String expediteur) {
        this.expediteur = expediteur;
    }

    
    @Column(name="objet")
    public String getObjet() {
        return this.objet;
    }
    
    public void setObjet(String objet) {
        this.objet = objet;
    }

    
    @Column(name="adresse_expediteur", length=45)
    public String getAdresseExpediteur() {
        return this.adresseExpediteur;
    }
    
    public void setAdresseExpediteur(String adresseExpediteur) {
        this.adresseExpediteur = adresseExpediteur;
    }

    
    @Column(name="importance")
    public Integer getImportance() {
        return this.importance;
    }
    
    public void setImportance(Integer importance) {
        this.importance = importance;
    }

    
    @Column(name="support", length=45)
    public String getSupport() {
        return this.support;
    }
    
    public void setSupport(String support) {
        this.support = support;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_emission", length=19)
    public Date getDateEmission() {
        return this.dateEmission;
    }
    
    public void setDateEmission(Date dateEmission) {
        this.dateEmission = dateEmission;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_enr", length=19)
    public Date getDateEnr() {
        return this.dateEnr;
    }
    
    public void setDateEnr(Date dateEnr) {
        this.dateEnr = dateEnr;
    }

    
    @Column(name="note")
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    
    @Column(name="statut")
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

    
    @Column(name="nature")
    public String getNature() {
        return this.nature;
    }
    
    public void setNature(String nature) {
        this.nature = nature;
    }

    
    @Column(name="entrant")
    public Boolean getEntrant() {
        return this.entrant;
    }
    
    public void setEntrant(Boolean entrant) {
        this.entrant = entrant;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="courrier")
    public Set<CourrierFichier> getCourrierFichiers() {
        return this.courrierFichiers;
    }
    
    public void setCourrierFichiers(Set<CourrierFichier> courrierFichiers) {
        this.courrierFichiers = courrierFichiers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="courrier")
    public Set<CourrierResponsable> getCourrierResponsables() {
        return this.courrierResponsables;
    }
    
    public void setCourrierResponsables(Set<CourrierResponsable> courrierResponsables) {
        this.courrierResponsables = courrierResponsables;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="courrier")
    public Set<CourrierProcedureEnCours> getCourrierProcedureEnCourses() {
        return this.courrierProcedureEnCourses;
    }
    
    public void setCourrierProcedureEnCourses(Set<CourrierProcedureEnCours> courrierProcedureEnCourses) {
        this.courrierProcedureEnCourses = courrierProcedureEnCourses;
    }




}


