package net.keama.workspace.entity;
// Generated Feb 4, 2017 1:33:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CourrierResponsableCommentaireFichier generated by hbm2java
 */
@Entity
@Table(name="courrier_responsable_commentaire_fichier"
    ,catalog="workspace"
)
public class CourrierResponsableCommentaireFichier  implements java.io.Serializable {


     private Integer idcourrierResponsableCommentaireFichier;
     private CourrierResponsableCommentaire courrierResponsableCommentaire;
     private String chemin;
     private String nom;
     private Date dateEnregistrement;
     private String statut;

    public CourrierResponsableCommentaireFichier() {
    }

    public CourrierResponsableCommentaireFichier(CourrierResponsableCommentaire courrierResponsableCommentaire, String chemin, String nom, Date dateEnregistrement, String statut) {
       this.courrierResponsableCommentaire = courrierResponsableCommentaire;
       this.chemin = chemin;
       this.nom = nom;
       this.dateEnregistrement = dateEnregistrement;
       this.statut = statut;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcourrier_responsable_commentaire_fichier", unique=true, nullable=false)
    public Integer getIdcourrierResponsableCommentaireFichier() {
        return this.idcourrierResponsableCommentaireFichier;
    }
    
    public void setIdcourrierResponsableCommentaireFichier(Integer idcourrierResponsableCommentaireFichier) {
        this.idcourrierResponsableCommentaireFichier = idcourrierResponsableCommentaireFichier;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcourrier_responsable_commentaire")
    public CourrierResponsableCommentaire getCourrierResponsableCommentaire() {
        return this.courrierResponsableCommentaire;
    }
    
    public void setCourrierResponsableCommentaire(CourrierResponsableCommentaire courrierResponsableCommentaire) {
        this.courrierResponsableCommentaire = courrierResponsableCommentaire;
    }

    
    @Column(name="chemin")
    public String getChemin() {
        return this.chemin;
    }
    
    public void setChemin(String chemin) {
        this.chemin = chemin;
    }

    
    @Column(name="nom", length=45)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_enregistrement", length=19)
    public Date getDateEnregistrement() {
        return this.dateEnregistrement;
    }
    
    public void setDateEnregistrement(Date dateEnregistrement) {
        this.dateEnregistrement = dateEnregistrement;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }




}


