package net.keama.workspace.entity;
// Generated Feb 4, 2017 1:33:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CourrierProcedureTache generated by hbm2java
 */
@Entity
@Table(name="courrier_procedure_tache"
    ,catalog="workspace"
)
public class CourrierProcedureTache  implements java.io.Serializable {


     private Integer idcourrierProcedureTache;
     private CourrierProcedure courrierProcedure;
     private Employe employe;
     private String ref;
     private String typeApprobation;
     private String commentaire;
     private Integer duree;
     private Integer ordre;
     private String libelle;
     private Set<CourrierResponsable> courrierResponsables = new HashSet<CourrierResponsable>(0);

    public CourrierProcedureTache() {
    }

    public CourrierProcedureTache(CourrierProcedure courrierProcedure, Employe employe, String ref, String typeApprobation, String commentaire, Integer duree, Integer ordre, String libelle, Set<CourrierResponsable> courrierResponsables) {
       this.courrierProcedure = courrierProcedure;
       this.employe = employe;
       this.ref = ref;
       this.typeApprobation = typeApprobation;
       this.commentaire = commentaire;
       this.duree = duree;
       this.ordre = ordre;
       this.libelle = libelle;
       this.courrierResponsables = courrierResponsables;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcourrier_procedure_tache", unique=true, nullable=false)
    public Integer getIdcourrierProcedureTache() {
        return this.idcourrierProcedureTache;
    }
    
    public void setIdcourrierProcedureTache(Integer idcourrierProcedureTache) {
        this.idcourrierProcedureTache = idcourrierProcedureTache;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idprocedure")
    public CourrierProcedure getCourrierProcedure() {
        return this.courrierProcedure;
    }
    
    public void setCourrierProcedure(CourrierProcedure courrierProcedure) {
        this.courrierProcedure = courrierProcedure;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idresponsable")
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }

    
    @Column(name="ref", length=45)
    public String getRef() {
        return this.ref;
    }
    
    public void setRef(String ref) {
        this.ref = ref;
    }

    
    @Column(name="type_approbation")
    public String getTypeApprobation() {
        return this.typeApprobation;
    }
    
    public void setTypeApprobation(String typeApprobation) {
        this.typeApprobation = typeApprobation;
    }

    
    @Column(name="commentaire")
    public String getCommentaire() {
        return this.commentaire;
    }
    
    public void setCommentaire(String commentaire) {
        this.commentaire = commentaire;
    }

    
    @Column(name="duree")
    public Integer getDuree() {
        return this.duree;
    }
    
    public void setDuree(Integer duree) {
        this.duree = duree;
    }

    
    @Column(name="ordre")
    public Integer getOrdre() {
        return this.ordre;
    }
    
    public void setOrdre(Integer ordre) {
        this.ordre = ordre;
    }

    
    @Column(name="libelle")
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="courrierProcedureTache")
    public Set<CourrierResponsable> getCourrierResponsables() {
        return this.courrierResponsables;
    }
    
    public void setCourrierResponsables(Set<CourrierResponsable> courrierResponsables) {
        this.courrierResponsables = courrierResponsables;
    }




}


