package net.keama.workspace.entity;
// Generated Feb 4, 2017 1:33:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CourrierResponsableCommentaire generated by hbm2java
 */
@Entity
@Table(name="courrier_responsable_commentaire"
    ,catalog="workspace"
)
public class CourrierResponsableCommentaire  implements java.io.Serializable {


     private Integer idcourrierResponsableCommentaire;
     private CourrierResponsable courrierResponsable;
     private String commentaire;
     private Date dateEnregistrement;
     private String statut;
     private Set<CourrierResponsableCommentaireFichier> courrierResponsableCommentaireFichiers = new HashSet<CourrierResponsableCommentaireFichier>(0);

    public CourrierResponsableCommentaire() {
    }

    public CourrierResponsableCommentaire(CourrierResponsable courrierResponsable, String commentaire, Date dateEnregistrement, String statut, Set<CourrierResponsableCommentaireFichier> courrierResponsableCommentaireFichiers) {
       this.courrierResponsable = courrierResponsable;
       this.commentaire = commentaire;
       this.dateEnregistrement = dateEnregistrement;
       this.statut = statut;
       this.courrierResponsableCommentaireFichiers = courrierResponsableCommentaireFichiers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcourrier_responsable_commentaire", unique=true, nullable=false)
    public Integer getIdcourrierResponsableCommentaire() {
        return this.idcourrierResponsableCommentaire;
    }
    
    public void setIdcourrierResponsableCommentaire(Integer idcourrierResponsableCommentaire) {
        this.idcourrierResponsableCommentaire = idcourrierResponsableCommentaire;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcourrier_responsable")
    public CourrierResponsable getCourrierResponsable() {
        return this.courrierResponsable;
    }
    
    public void setCourrierResponsable(CourrierResponsable courrierResponsable) {
        this.courrierResponsable = courrierResponsable;
    }

    
    @Column(name="commentaire")
    public String getCommentaire() {
        return this.commentaire;
    }
    
    public void setCommentaire(String commentaire) {
        this.commentaire = commentaire;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_enregistrement", length=19)
    public Date getDateEnregistrement() {
        return this.dateEnregistrement;
    }
    
    public void setDateEnregistrement(Date dateEnregistrement) {
        this.dateEnregistrement = dateEnregistrement;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="courrierResponsableCommentaire")
    public Set<CourrierResponsableCommentaireFichier> getCourrierResponsableCommentaireFichiers() {
        return this.courrierResponsableCommentaireFichiers;
    }
    
    public void setCourrierResponsableCommentaireFichiers(Set<CourrierResponsableCommentaireFichier> courrierResponsableCommentaireFichiers) {
        this.courrierResponsableCommentaireFichiers = courrierResponsableCommentaireFichiers;
    }




}


