package net.keama.workspace.entity;
// Generated Feb 4, 2017 1:33:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CourrierProcedureEnCours generated by hbm2java
 */
@Entity
@Table(name="courrier_procedure_en_cours"
    ,catalog="workspace"
)
public class CourrierProcedureEnCours  implements java.io.Serializable {


     private Integer idcourrierProcedureEnCours;
     private Courrier courrier;
     private CourrierProcedure courrierProcedure;
     private String ref;
     private Date dateDebut;
     private String statut;
     private Set<CourrierResponsable> courrierResponsables = new HashSet<CourrierResponsable>(0);

    public CourrierProcedureEnCours() {
    }

    public CourrierProcedureEnCours(Courrier courrier, CourrierProcedure courrierProcedure, String ref, Date dateDebut, String statut, Set<CourrierResponsable> courrierResponsables) {
       this.courrier = courrier;
       this.courrierProcedure = courrierProcedure;
       this.ref = ref;
       this.dateDebut = dateDebut;
       this.statut = statut;
       this.courrierResponsables = courrierResponsables;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcourrier_procedure_en_cours", unique=true, nullable=false)
    public Integer getIdcourrierProcedureEnCours() {
        return this.idcourrierProcedureEnCours;
    }
    
    public void setIdcourrierProcedureEnCours(Integer idcourrierProcedureEnCours) {
        this.idcourrierProcedureEnCours = idcourrierProcedureEnCours;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcourrier")
    public Courrier getCourrier() {
        return this.courrier;
    }
    
    public void setCourrier(Courrier courrier) {
        this.courrier = courrier;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idprocedure")
    public CourrierProcedure getCourrierProcedure() {
        return this.courrierProcedure;
    }
    
    public void setCourrierProcedure(CourrierProcedure courrierProcedure) {
        this.courrierProcedure = courrierProcedure;
    }

    
    @Column(name="ref", length=45)
    public String getRef() {
        return this.ref;
    }
    
    public void setRef(String ref) {
        this.ref = ref;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_debut", length=19)
    public Date getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="courrierProcedureEnCours")
    public Set<CourrierResponsable> getCourrierResponsables() {
        return this.courrierResponsables;
    }
    
    public void setCourrierResponsables(Set<CourrierResponsable> courrierResponsables) {
        this.courrierResponsables = courrierResponsables;
    }




}


