package net.keama.workspace.entity;
// Generated Feb 4, 2017 1:33:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * CourrierProcedure generated by hbm2java
 */
@Entity
@Table(name="courrier_procedure"
    ,catalog="workspace"
    , uniqueConstraints = @UniqueConstraint(columnNames="type_courrier") 
)
public class CourrierProcedure  implements java.io.Serializable {


     private Integer idcourrierProcedure;
     private CourrierType courrierType;
     private String ref;
     private String nom;
     private String description;
     private String statut;
     private Set<CourrierProcedureEnCours> courrierProcedureEnCourses = new HashSet<CourrierProcedureEnCours>(0);
     private Set<CourrierProcedureTache> courrierProcedureTaches = new HashSet<CourrierProcedureTache>(0);

    public CourrierProcedure() {
    }

	
    public CourrierProcedure(CourrierType courrierType) {
        this.courrierType = courrierType;
    }
    public CourrierProcedure(CourrierType courrierType, String ref, String nom, String description, String statut, Set<CourrierProcedureEnCours> courrierProcedureEnCourses, Set<CourrierProcedureTache> courrierProcedureTaches) {
       this.courrierType = courrierType;
       this.ref = ref;
       this.nom = nom;
       this.description = description;
       this.statut = statut;
       this.courrierProcedureEnCourses = courrierProcedureEnCourses;
       this.courrierProcedureTaches = courrierProcedureTaches;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcourrier_procedure", unique=true, nullable=false)
    public Integer getIdcourrierProcedure() {
        return this.idcourrierProcedure;
    }
    
    public void setIdcourrierProcedure(Integer idcourrierProcedure) {
        this.idcourrierProcedure = idcourrierProcedure;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="type_courrier", unique=true, nullable=false)
    public CourrierType getCourrierType() {
        return this.courrierType;
    }
    
    public void setCourrierType(CourrierType courrierType) {
        this.courrierType = courrierType;
    }

    
    @Column(name="ref", length=45)
    public String getRef() {
        return this.ref;
    }
    
    public void setRef(String ref) {
        this.ref = ref;
    }

    
    @Column(name="nom")
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="courrierProcedure")
    public Set<CourrierProcedureEnCours> getCourrierProcedureEnCourses() {
        return this.courrierProcedureEnCourses;
    }
    
    public void setCourrierProcedureEnCourses(Set<CourrierProcedureEnCours> courrierProcedureEnCourses) {
        this.courrierProcedureEnCourses = courrierProcedureEnCourses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="courrierProcedure")
    public Set<CourrierProcedureTache> getCourrierProcedureTaches() {
        return this.courrierProcedureTaches;
    }
    
    public void setCourrierProcedureTaches(Set<CourrierProcedureTache> courrierProcedureTaches) {
        this.courrierProcedureTaches = courrierProcedureTaches;
    }




}


