package net.keama.workspace.entity;
// Generated Feb 4, 2017 1:33:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Entreprise generated by hbm2java
 */
@Entity
@Table(name="entreprise"
    ,catalog="workspace"
    , uniqueConstraints = @UniqueConstraint(columnNames="nom") 
)
public class Entreprise  implements java.io.Serializable {


     private Integer identreprise;
     private ImageLogo imageLogo;
     private Utilisateur utilisateur;
     private String nom;
     private String sigle;
     private String adresse;
     private String adresseComplement;
     private String bp;
     private String tel1;
     private String tel2;
     private String tel3;
     private String fax;
     private String email1;
     private String email2;
     private String email3;
     private Date dateCreation;
     private String numeroContribuable;
     private Set<Site> sites = new HashSet<Site>(0);

    public Entreprise() {
    }

    public Entreprise(ImageLogo imageLogo, Utilisateur utilisateur, String nom, String sigle, String adresse, String adresseComplement, String bp, String tel1, String tel2, String tel3, String fax, String email1, String email2, String email3, Date dateCreation, String numeroContribuable, Set<Site> sites) {
       this.imageLogo = imageLogo;
       this.utilisateur = utilisateur;
       this.nom = nom;
       this.sigle = sigle;
       this.adresse = adresse;
       this.adresseComplement = adresseComplement;
       this.bp = bp;
       this.tel1 = tel1;
       this.tel2 = tel2;
       this.tel3 = tel3;
       this.fax = fax;
       this.email1 = email1;
       this.email2 = email2;
       this.email3 = email3;
       this.dateCreation = dateCreation;
       this.numeroContribuable = numeroContribuable;
       this.sites = sites;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="identreprise", unique=true, nullable=false)
    public Integer getIdentreprise() {
        return this.identreprise;
    }
    
    public void setIdentreprise(Integer identreprise) {
        this.identreprise = identreprise;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idimage_logo")
    public ImageLogo getImageLogo() {
        return this.imageLogo;
    }
    
    public void setImageLogo(ImageLogo imageLogo) {
        this.imageLogo = imageLogo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idutilisateur")
    public Utilisateur getUtilisateur() {
        return this.utilisateur;
    }
    
    public void setUtilisateur(Utilisateur utilisateur) {
        this.utilisateur = utilisateur;
    }

    
    @Column(name="nom", unique=true, length=45)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="sigle", length=45)
    public String getSigle() {
        return this.sigle;
    }
    
    public void setSigle(String sigle) {
        this.sigle = sigle;
    }

    
    @Column(name="adresse", length=45)
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="adresse_complement", length=45)
    public String getAdresseComplement() {
        return this.adresseComplement;
    }
    
    public void setAdresseComplement(String adresseComplement) {
        this.adresseComplement = adresseComplement;
    }

    
    @Column(name="bp", length=45)
    public String getBp() {
        return this.bp;
    }
    
    public void setBp(String bp) {
        this.bp = bp;
    }

    
    @Column(name="tel1", length=45)
    public String getTel1() {
        return this.tel1;
    }
    
    public void setTel1(String tel1) {
        this.tel1 = tel1;
    }

    
    @Column(name="tel2", length=45)
    public String getTel2() {
        return this.tel2;
    }
    
    public void setTel2(String tel2) {
        this.tel2 = tel2;
    }

    
    @Column(name="tel3", length=45)
    public String getTel3() {
        return this.tel3;
    }
    
    public void setTel3(String tel3) {
        this.tel3 = tel3;
    }

    
    @Column(name="fax", length=45)
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    
    @Column(name="email1", length=45)
    public String getEmail1() {
        return this.email1;
    }
    
    public void setEmail1(String email1) {
        this.email1 = email1;
    }

    
    @Column(name="email2", length=45)
    public String getEmail2() {
        return this.email2;
    }
    
    public void setEmail2(String email2) {
        this.email2 = email2;
    }

    
    @Column(name="email3", length=45)
    public String getEmail3() {
        return this.email3;
    }
    
    public void setEmail3(String email3) {
        this.email3 = email3;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_creation", length=10)
    public Date getDateCreation() {
        return this.dateCreation;
    }
    
    public void setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }

    
    @Column(name="numero_contribuable", length=45)
    public String getNumeroContribuable() {
        return this.numeroContribuable;
    }
    
    public void setNumeroContribuable(String numeroContribuable) {
        this.numeroContribuable = numeroContribuable;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="entreprise")
    public Set<Site> getSites() {
        return this.sites;
    }
    
    public void setSites(Set<Site> sites) {
        this.sites = sites;
    }




}


