package net.keama.workspace.entity;
// Generated Feb 4, 2017 1:33:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ImageLogo generated by hbm2java
 */
@Entity
@Table(name="image_logo"
    ,catalog="workspace"
    , uniqueConstraints = @UniqueConstraint(columnNames="nom") 
)
public class ImageLogo  implements java.io.Serializable {


     private Integer idimageLogo;
     private String nom;
     private String chemin;
     private String extension;
     private Integer poidsKo;
     private Date dateEnr;
     private Set<Structure> structures = new HashSet<Structure>(0);
     private Set<Employe> employes = new HashSet<Employe>(0);
     private Set<Entreprise> entreprises = new HashSet<Entreprise>(0);

    public ImageLogo() {
    }

    public ImageLogo(String nom, String chemin, String extension, Integer poidsKo, Date dateEnr, Set<Structure> structures, Set<Employe> employes, Set<Entreprise> entreprises) {
       this.nom = nom;
       this.chemin = chemin;
       this.extension = extension;
       this.poidsKo = poidsKo;
       this.dateEnr = dateEnr;
       this.structures = structures;
       this.employes = employes;
       this.entreprises = entreprises;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idimage_logo", unique=true, nullable=false)
    public Integer getIdimageLogo() {
        return this.idimageLogo;
    }
    
    public void setIdimageLogo(Integer idimageLogo) {
        this.idimageLogo = idimageLogo;
    }

    
    @Column(name="nom", unique=true, length=45)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="chemin")
    public String getChemin() {
        return this.chemin;
    }
    
    public void setChemin(String chemin) {
        this.chemin = chemin;
    }

    
    @Column(name="extension", length=45)
    public String getExtension() {
        return this.extension;
    }
    
    public void setExtension(String extension) {
        this.extension = extension;
    }

    
    @Column(name="poidsKo")
    public Integer getPoidsKo() {
        return this.poidsKo;
    }
    
    public void setPoidsKo(Integer poidsKo) {
        this.poidsKo = poidsKo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_enr", length=19)
    public Date getDateEnr() {
        return this.dateEnr;
    }
    
    public void setDateEnr(Date dateEnr) {
        this.dateEnr = dateEnr;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="imageLogo")
    public Set<Structure> getStructures() {
        return this.structures;
    }
    
    public void setStructures(Set<Structure> structures) {
        this.structures = structures;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="imageLogo")
    public Set<Employe> getEmployes() {
        return this.employes;
    }
    
    public void setEmployes(Set<Employe> employes) {
        this.employes = employes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="imageLogo")
    public Set<Entreprise> getEntreprises() {
        return this.entreprises;
    }
    
    public void setEntreprises(Set<Entreprise> entreprises) {
        this.entreprises = entreprises;
    }




}


