package net.keama.workspace.entity;
// Generated Feb 4, 2017 1:33:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * InformationGenerale generated by hbm2java
 */
@Entity
@Table(name="information_generale"
    ,catalog="workspace"
)
public class InformationGenerale  implements java.io.Serializable {


     private Integer idinformationGenerale;
     private Employe employe;
     private String titre;
     private String contenu;
     private Date dateEnregistrement;
     private String statut;
     private Set<InformationGeneraleDocument> informationGeneraleDocuments = new HashSet<InformationGeneraleDocument>(0);
     private Set<InformationGeneraleEmploye> informationGeneraleEmployes = new HashSet<InformationGeneraleEmploye>(0);

    public InformationGenerale() {
    }

    public InformationGenerale(Employe employe, String titre, String contenu, Date dateEnregistrement, String statut, Set<InformationGeneraleDocument> informationGeneraleDocuments, Set<InformationGeneraleEmploye> informationGeneraleEmployes) {
       this.employe = employe;
       this.titre = titre;
       this.contenu = contenu;
       this.dateEnregistrement = dateEnregistrement;
       this.statut = statut;
       this.informationGeneraleDocuments = informationGeneraleDocuments;
       this.informationGeneraleEmployes = informationGeneraleEmployes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idinformation_generale", unique=true, nullable=false)
    public Integer getIdinformationGenerale() {
        return this.idinformationGenerale;
    }
    
    public void setIdinformationGenerale(Integer idinformationGenerale) {
        this.idinformationGenerale = idinformationGenerale;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idemploye")
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }

    
    @Column(name="titre", length=45)
    public String getTitre() {
        return this.titre;
    }
    
    public void setTitre(String titre) {
        this.titre = titre;
    }

    
    @Column(name="contenu")
    public String getContenu() {
        return this.contenu;
    }
    
    public void setContenu(String contenu) {
        this.contenu = contenu;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_enregistrement", length=19)
    public Date getDateEnregistrement() {
        return this.dateEnregistrement;
    }
    
    public void setDateEnregistrement(Date dateEnregistrement) {
        this.dateEnregistrement = dateEnregistrement;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="informationGenerale")
    public Set<InformationGeneraleDocument> getInformationGeneraleDocuments() {
        return this.informationGeneraleDocuments;
    }
    
    public void setInformationGeneraleDocuments(Set<InformationGeneraleDocument> informationGeneraleDocuments) {
        this.informationGeneraleDocuments = informationGeneraleDocuments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="informationGenerale")
    public Set<InformationGeneraleEmploye> getInformationGeneraleEmployes() {
        return this.informationGeneraleEmployes;
    }
    
    public void setInformationGeneraleEmployes(Set<InformationGeneraleEmploye> informationGeneraleEmployes) {
        this.informationGeneraleEmployes = informationGeneraleEmployes;
    }




}


