package net.keama.workspace.entity;
// Generated Feb 4, 2017 1:33:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * InformationGeneraleEmploye generated by hbm2java
 */
@Entity
@Table(name="information_generale_employe"
    ,catalog="workspace"
)
public class InformationGeneraleEmploye  implements java.io.Serializable {


     private Integer idinformationGeneraleEmploye;
     private Employe employe;
     private InformationGenerale informationGenerale;
     private String statut;

    public InformationGeneraleEmploye() {
    }

    public InformationGeneraleEmploye(Employe employe, InformationGenerale informationGenerale, String statut) {
       this.employe = employe;
       this.informationGenerale = informationGenerale;
       this.statut = statut;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idinformation_generale_employe", unique=true, nullable=false)
    public Integer getIdinformationGeneraleEmploye() {
        return this.idinformationGeneraleEmploye;
    }
    
    public void setIdinformationGeneraleEmploye(Integer idinformationGeneraleEmploye) {
        this.idinformationGeneraleEmploye = idinformationGeneraleEmploye;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idemploye")
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idinformation_generale")
    public InformationGenerale getInformationGenerale() {
        return this.informationGenerale;
    }
    
    public void setInformationGenerale(InformationGenerale informationGenerale) {
        this.informationGenerale = informationGenerale;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }




}


