package net.keama.workspace.entity;
// Generated Feb 4, 2017 1:33:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MessageFichier generated by hbm2java
 */
@Entity
@Table(name="message_fichier"
    ,catalog="workspace"
)
public class MessageFichier  implements java.io.Serializable {


     private Integer idmessageFichier;
     private Message message;
     private String chemin;
     private String nom;
     private Date dateEnregistrement;
     private String statut;

    public MessageFichier() {
    }

    public MessageFichier(Message message, String chemin, String nom, Date dateEnregistrement, String statut) {
       this.message = message;
       this.chemin = chemin;
       this.nom = nom;
       this.dateEnregistrement = dateEnregistrement;
       this.statut = statut;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idmessage_fichier", unique=true, nullable=false)
    public Integer getIdmessageFichier() {
        return this.idmessageFichier;
    }
    
    public void setIdmessageFichier(Integer idmessageFichier) {
        this.idmessageFichier = idmessageFichier;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idmessage")
    public Message getMessage() {
        return this.message;
    }
    
    public void setMessage(Message message) {
        this.message = message;
    }

    
    @Column(name="chemin", length=245)
    public String getChemin() {
        return this.chemin;
    }
    
    public void setChemin(String chemin) {
        this.chemin = chemin;
    }

    
    @Column(name="nom")
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_enregistrement", length=19)
    public Date getDateEnregistrement() {
        return this.dateEnregistrement;
    }
    
    public void setDateEnregistrement(Date dateEnregistrement) {
        this.dateEnregistrement = dateEnregistrement;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }




}


