package net.keama.workspace.entity;
// Generated Feb 4, 2017 1:33:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Poste generated by hbm2java
 */
@Entity
@Table(name="poste"
    ,catalog="workspace"
    , uniqueConstraints = {@UniqueConstraint(columnNames="sigle"), @UniqueConstraint(columnNames="libelle")} 
)
public class Poste  implements java.io.Serializable {


     private Integer idposte;
     private Poste poste;
     private Structure structure;
     private String libelle;
     private String sigle;
     private Boolean estChefStructure;
     private Set<Employe> employes = new HashSet<Employe>(0);
     private Set<Poste> postes = new HashSet<Poste>(0);

    public Poste() {
    }

    public Poste(Poste poste, Structure structure, String libelle, String sigle, Boolean estChefStructure, Set<Employe> employes, Set<Poste> postes) {
       this.poste = poste;
       this.structure = structure;
       this.libelle = libelle;
       this.sigle = sigle;
       this.estChefStructure = estChefStructure;
       this.employes = employes;
       this.postes = postes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idposte", unique=true, nullable=false)
    public Integer getIdposte() {
        return this.idposte;
    }
    
    public void setIdposte(Integer idposte) {
        this.idposte = idposte;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idposte_parent")
    public Poste getPoste() {
        return this.poste;
    }
    
    public void setPoste(Poste poste) {
        this.poste = poste;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idstructure")
    public Structure getStructure() {
        return this.structure;
    }
    
    public void setStructure(Structure structure) {
        this.structure = structure;
    }

    
    @Column(name="libelle", unique=true, length=105)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="sigle", unique=true, length=45)
    public String getSigle() {
        return this.sigle;
    }
    
    public void setSigle(String sigle) {
        this.sigle = sigle;
    }

    
    @Column(name="estChefStructure")
    public Boolean getEstChefStructure() {
        return this.estChefStructure;
    }
    
    public void setEstChefStructure(Boolean estChefStructure) {
        this.estChefStructure = estChefStructure;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="poste")
    public Set<Employe> getEmployes() {
        return this.employes;
    }
    
    public void setEmployes(Set<Employe> employes) {
        this.employes = employes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="poste")
    public Set<Poste> getPostes() {
        return this.postes;
    }
    
    public void setPostes(Set<Poste> postes) {
        this.postes = postes;
    }




}


