package net.keama.workspace.entity;
// Generated Feb 4, 2017 1:33:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProcedureEffective generated by hbm2java
 */
@Entity
@Table(name="procedure_effective"
    ,catalog="workspace"
)
public class ProcedureEffective  implements java.io.Serializable {


     private Integer idprocedureEffective;
     private Procedures procedures;
     private Date dateDebut;
     private String ref;
     private String statut;
     private Date dateFin;
     private Set<TacheProcedureEffectue> tacheProcedureEffectues = new HashSet<TacheProcedureEffectue>(0);

    public ProcedureEffective() {
    }

    public ProcedureEffective(Procedures procedures, Date dateDebut, String ref, String statut, Date dateFin, Set<TacheProcedureEffectue> tacheProcedureEffectues) {
       this.procedures = procedures;
       this.dateDebut = dateDebut;
       this.ref = ref;
       this.statut = statut;
       this.dateFin = dateFin;
       this.tacheProcedureEffectues = tacheProcedureEffectues;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idprocedure_effective", unique=true, nullable=false)
    public Integer getIdprocedureEffective() {
        return this.idprocedureEffective;
    }
    
    public void setIdprocedureEffective(Integer idprocedureEffective) {
        this.idprocedureEffective = idprocedureEffective;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idprocedure")
    public Procedures getProcedures() {
        return this.procedures;
    }
    
    public void setProcedures(Procedures procedures) {
        this.procedures = procedures;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_debut", length=19)
    public Date getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }

    
    @Column(name="ref", length=45)
    public String getRef() {
        return this.ref;
    }
    
    public void setRef(String ref) {
        this.ref = ref;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_fin", length=19)
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="procedureEffective")
    public Set<TacheProcedureEffectue> getTacheProcedureEffectues() {
        return this.tacheProcedureEffectues;
    }
    
    public void setTacheProcedureEffectues(Set<TacheProcedureEffectue> tacheProcedureEffectues) {
        this.tacheProcedureEffectues = tacheProcedureEffectues;
    }




}


