package net.keama.workspace.entity;
// Generated Feb 4, 2017 1:33:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Procedures generated by hbm2java
 */
@Entity
@Table(name="procedures"
    ,catalog="workspace"
)
public class Procedures  implements java.io.Serializable {


     private Integer idprocedures;
     private String nom;
     private String statut;
     private Set<TacheProcedure> tacheProcedures = new HashSet<TacheProcedure>(0);
     private Set<ProcedureEffective> procedureEffectives = new HashSet<ProcedureEffective>(0);

    public Procedures() {
    }

    public Procedures(String nom, String statut, Set<TacheProcedure> tacheProcedures, Set<ProcedureEffective> procedureEffectives) {
       this.nom = nom;
       this.statut = statut;
       this.tacheProcedures = tacheProcedures;
       this.procedureEffectives = procedureEffectives;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idprocedures", unique=true, nullable=false)
    public Integer getIdprocedures() {
        return this.idprocedures;
    }
    
    public void setIdprocedures(Integer idprocedures) {
        this.idprocedures = idprocedures;
    }

    
    @Column(name="nom", length=45)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="procedures")
    public Set<TacheProcedure> getTacheProcedures() {
        return this.tacheProcedures;
    }
    
    public void setTacheProcedures(Set<TacheProcedure> tacheProcedures) {
        this.tacheProcedures = tacheProcedures;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="procedures")
    public Set<ProcedureEffective> getProcedureEffectives() {
        return this.procedureEffectives;
    }
    
    public void setProcedureEffectives(Set<ProcedureEffective> procedureEffectives) {
        this.procedureEffectives = procedureEffectives;
    }




}


