package net.keama.workspace.entity;
// Generated Feb 4, 2017 1:33:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ReunionEmploye generated by hbm2java
 */
@Entity
@Table(name="reunion_employe"
    ,catalog="workspace"
)
public class ReunionEmploye  implements java.io.Serializable {


     private Integer idreunionEmploye;
     private Employe employe;
     private Reunion reunion;
     private String statut;

    public ReunionEmploye() {
    }

    public ReunionEmploye(Employe employe, Reunion reunion, String statut) {
       this.employe = employe;
       this.reunion = reunion;
       this.statut = statut;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idreunion_employe", unique=true, nullable=false)
    public Integer getIdreunionEmploye() {
        return this.idreunionEmploye;
    }
    
    public void setIdreunionEmploye(Integer idreunionEmploye) {
        this.idreunionEmploye = idreunionEmploye;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idemploye")
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idreunion")
    public Reunion getReunion() {
        return this.reunion;
    }
    
    public void setReunion(Reunion reunion) {
        this.reunion = reunion;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }




}


