package net.keama.workspace.entity;
// Generated Feb 4, 2017 1:33:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ReunionRapport generated by hbm2java
 */
@Entity
@Table(name="reunion_rapport"
    ,catalog="workspace"
)
public class ReunionRapport  implements java.io.Serializable {


     private Integer idreunionRapport;
     private Reunion reunion;
     private String nom;
     private String chemin;
     private Date dateEnregistrement;
     private String statut;

    public ReunionRapport() {
    }

    public ReunionRapport(Reunion reunion, String nom, String chemin, Date dateEnregistrement, String statut) {
       this.reunion = reunion;
       this.nom = nom;
       this.chemin = chemin;
       this.dateEnregistrement = dateEnregistrement;
       this.statut = statut;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idreunion_rapport", unique=true, nullable=false)
    public Integer getIdreunionRapport() {
        return this.idreunionRapport;
    }
    
    public void setIdreunionRapport(Integer idreunionRapport) {
        this.idreunionRapport = idreunionRapport;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idreunion")
    public Reunion getReunion() {
        return this.reunion;
    }
    
    public void setReunion(Reunion reunion) {
        this.reunion = reunion;
    }

    
    @Column(name="nom", length=45)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="chemin")
    public String getChemin() {
        return this.chemin;
    }
    
    public void setChemin(String chemin) {
        this.chemin = chemin;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_enregistrement", length=19)
    public Date getDateEnregistrement() {
        return this.dateEnregistrement;
    }
    
    public void setDateEnregistrement(Date dateEnregistrement) {
        this.dateEnregistrement = dateEnregistrement;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }




}


