package net.keama.workspace.entity;
// Generated Feb 4, 2017 1:33:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SalleReunion generated by hbm2java
 */
@Entity
@Table(name="salle_reunion"
    ,catalog="workspace"
)
public class SalleReunion  implements java.io.Serializable {


     private Integer idsalleReunion;
     private String nom;
     private Integer capacite;
     private String statut;
     private Set<Reunion> reunions = new HashSet<Reunion>(0);

    public SalleReunion() {
    }

    public SalleReunion(String nom, Integer capacite, String statut, Set<Reunion> reunions) {
       this.nom = nom;
       this.capacite = capacite;
       this.statut = statut;
       this.reunions = reunions;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idsalle_reunion", unique=true, nullable=false)
    public Integer getIdsalleReunion() {
        return this.idsalleReunion;
    }
    
    public void setIdsalleReunion(Integer idsalleReunion) {
        this.idsalleReunion = idsalleReunion;
    }

    
    @Column(name="nom", length=45)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="capacite")
    public Integer getCapacite() {
        return this.capacite;
    }
    
    public void setCapacite(Integer capacite) {
        this.capacite = capacite;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="salleReunion")
    public Set<Reunion> getReunions() {
        return this.reunions;
    }
    
    public void setReunions(Set<Reunion> reunions) {
        this.reunions = reunions;
    }




}


