package net.keama.workspace.entity;
// Generated Feb 4, 2017 1:33:29 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TacheEmploye generated by hbm2java
 */
@Entity
@Table(name="tache_employe"
    ,catalog="workspace"
)
public class TacheEmploye  implements java.io.Serializable {


     private Integer idtacheEmploye;
     private Employe employe;
     private Tache tache;
     private String statut;

    public TacheEmploye() {
    }

    public TacheEmploye(Employe employe, Tache tache, String statut) {
       this.employe = employe;
       this.tache = tache;
       this.statut = statut;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idtache_employe", unique=true, nullable=false)
    public Integer getIdtacheEmploye() {
        return this.idtacheEmploye;
    }
    
    public void setIdtacheEmploye(Integer idtacheEmploye) {
        this.idtacheEmploye = idtacheEmploye;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idemploye")
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idtache")
    public Tache getTache() {
        return this.tache;
    }
    
    public void setTache(Tache tache) {
        this.tache = tache;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }




}


