package net.keama.workspace.entity;
// Generated Feb 4, 2017 1:33:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TacheProcedure generated by hbm2java
 */
@Entity
@Table(name="tache_procedure"
    ,catalog="workspace"
)
public class TacheProcedure  implements java.io.Serializable {


     private Integer idtacheProcedure;
     private Employe employe;
     private Procedures procedures;
     private String libelle;
     private String description;
     private Integer dureeEnJour;
     private Integer ordre;
     private Set<TacheProcedureEffectue> tacheProcedureEffectues = new HashSet<TacheProcedureEffectue>(0);

    public TacheProcedure() {
    }

    public TacheProcedure(Employe employe, Procedures procedures, String libelle, String description, Integer dureeEnJour, Integer ordre, Set<TacheProcedureEffectue> tacheProcedureEffectues) {
       this.employe = employe;
       this.procedures = procedures;
       this.libelle = libelle;
       this.description = description;
       this.dureeEnJour = dureeEnJour;
       this.ordre = ordre;
       this.tacheProcedureEffectues = tacheProcedureEffectues;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idtache_procedure", unique=true, nullable=false)
    public Integer getIdtacheProcedure() {
        return this.idtacheProcedure;
    }
    
    public void setIdtacheProcedure(Integer idtacheProcedure) {
        this.idtacheProcedure = idtacheProcedure;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idemploye")
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idprocedure")
    public Procedures getProcedures() {
        return this.procedures;
    }
    
    public void setProcedures(Procedures procedures) {
        this.procedures = procedures;
    }

    
    @Column(name="libelle", length=45)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="duree_en_jour")
    public Integer getDureeEnJour() {
        return this.dureeEnJour;
    }
    
    public void setDureeEnJour(Integer dureeEnJour) {
        this.dureeEnJour = dureeEnJour;
    }

    
    @Column(name="ordre")
    public Integer getOrdre() {
        return this.ordre;
    }
    
    public void setOrdre(Integer ordre) {
        this.ordre = ordre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tacheProcedure")
    public Set<TacheProcedureEffectue> getTacheProcedureEffectues() {
        return this.tacheProcedureEffectues;
    }
    
    public void setTacheProcedureEffectues(Set<TacheProcedureEffectue> tacheProcedureEffectues) {
        this.tacheProcedureEffectues = tacheProcedureEffectues;
    }




}


