package net.keama.workspace.entity;
// Generated Feb 4, 2017 1:33:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TacheProcedureEffectue generated by hbm2java
 */
@Entity
@Table(name="tache_procedure_effectue"
    ,catalog="workspace"
)
public class TacheProcedureEffectue  implements java.io.Serializable {


     private Integer idtacheProcedureEffectue;
     private ProcedureEffective procedureEffective;
     private TacheProcedure tacheProcedure;
     private Date dateDebut;
     private Date dateFin;
     private String statut;

    public TacheProcedureEffectue() {
    }

    public TacheProcedureEffectue(ProcedureEffective procedureEffective, TacheProcedure tacheProcedure, Date dateDebut, Date dateFin, String statut) {
       this.procedureEffective = procedureEffective;
       this.tacheProcedure = tacheProcedure;
       this.dateDebut = dateDebut;
       this.dateFin = dateFin;
       this.statut = statut;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idtache_procedure_effectue", unique=true, nullable=false)
    public Integer getIdtacheProcedureEffectue() {
        return this.idtacheProcedureEffectue;
    }
    
    public void setIdtacheProcedureEffectue(Integer idtacheProcedureEffectue) {
        this.idtacheProcedureEffectue = idtacheProcedureEffectue;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idprocedureEffective")
    public ProcedureEffective getProcedureEffective() {
        return this.procedureEffective;
    }
    
    public void setProcedureEffective(ProcedureEffective procedureEffective) {
        this.procedureEffective = procedureEffective;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idtache_procedure")
    public TacheProcedure getTacheProcedure() {
        return this.tacheProcedure;
    }
    
    public void setTacheProcedure(TacheProcedure tacheProcedure) {
        this.tacheProcedure = tacheProcedure;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_debut", length=19)
    public Date getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_fin", length=19)
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }




}


