package net.keama.workspace.entity;
// Generated Feb 4, 2017 1:33:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tache generated by hbm2java
 */
@Entity
@Table(name="tache"
    ,catalog="workspace"
)
public class Tache  implements java.io.Serializable {


     private Integer idtache;
     private Employe employeByIdordonnateur;
     private Employe employeByIdemploye;
     private String libelle;
     private String description;
     private Date dateEmission;
     private Date dateDebut;
     private Date dateFin;
     private String statut;
     private Date dateTerminee;
     private Set<TacheDocument> tacheDocuments = new HashSet<TacheDocument>(0);
     private Set<TacheCommentaire> tacheCommentaires = new HashSet<TacheCommentaire>(0);
     private Set<TacheEmploye> tacheEmployes = new HashSet<TacheEmploye>(0);

    public Tache() {
    }

    public Tache(Employe employeByIdordonnateur, Employe employeByIdemploye, String libelle, String description, Date dateEmission, Date dateDebut, Date dateFin, String statut, Date dateTerminee, Set<TacheDocument> tacheDocuments, Set<TacheCommentaire> tacheCommentaires, Set<TacheEmploye> tacheEmployes) {
       this.employeByIdordonnateur = employeByIdordonnateur;
       this.employeByIdemploye = employeByIdemploye;
       this.libelle = libelle;
       this.description = description;
       this.dateEmission = dateEmission;
       this.dateDebut = dateDebut;
       this.dateFin = dateFin;
       this.statut = statut;
       this.dateTerminee = dateTerminee;
       this.tacheDocuments = tacheDocuments;
       this.tacheCommentaires = tacheCommentaires;
       this.tacheEmployes = tacheEmployes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idtache", unique=true, nullable=false)
    public Integer getIdtache() {
        return this.idtache;
    }
    
    public void setIdtache(Integer idtache) {
        this.idtache = idtache;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idordonnateur")
    public Employe getEmployeByIdordonnateur() {
        return this.employeByIdordonnateur;
    }
    
    public void setEmployeByIdordonnateur(Employe employeByIdordonnateur) {
        this.employeByIdordonnateur = employeByIdordonnateur;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idemploye")
    public Employe getEmployeByIdemploye() {
        return this.employeByIdemploye;
    }
    
    public void setEmployeByIdemploye(Employe employeByIdemploye) {
        this.employeByIdemploye = employeByIdemploye;
    }

    
    @Column(name="libelle", length=45)
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_emission", length=19)
    public Date getDateEmission() {
        return this.dateEmission;
    }
    
    public void setDateEmission(Date dateEmission) {
        this.dateEmission = dateEmission;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_debut", length=19)
    public Date getDateDebut() {
        return this.dateDebut;
    }
    
    public void setDateDebut(Date dateDebut) {
        this.dateDebut = dateDebut;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_fin", length=19)
    public Date getDateFin() {
        return this.dateFin;
    }
    
    public void setDateFin(Date dateFin) {
        this.dateFin = dateFin;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_terminee", length=19)
    public Date getDateTerminee() {
        return this.dateTerminee;
    }
    
    public void setDateTerminee(Date dateTerminee) {
        this.dateTerminee = dateTerminee;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tache")
    public Set<TacheDocument> getTacheDocuments() {
        return this.tacheDocuments;
    }
    
    public void setTacheDocuments(Set<TacheDocument> tacheDocuments) {
        this.tacheDocuments = tacheDocuments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tache")
    public Set<TacheCommentaire> getTacheCommentaires() {
        return this.tacheCommentaires;
    }
    
    public void setTacheCommentaires(Set<TacheCommentaire> tacheCommentaires) {
        this.tacheCommentaires = tacheCommentaires;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tache")
    public Set<TacheEmploye> getTacheEmployes() {
        return this.tacheEmployes;
    }
    
    public void setTacheEmployes(Set<TacheEmploye> tacheEmployes) {
        this.tacheEmployes = tacheEmployes;
    }




}


