package net.keama.workspace.entity;
// Generated Feb 4, 2017 1:33:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TacheCommentaire generated by hbm2java
 */
@Entity
@Table(name="tache_commentaire"
    ,catalog="workspace"
)
public class TacheCommentaire  implements java.io.Serializable {


     private Integer idtacheCommentaire;
     private Employe employe;
     private Tache tache;
     private String contenu;
     private Date datePublication;
     private String statut;

    public TacheCommentaire() {
    }

    public TacheCommentaire(Employe employe, Tache tache, String contenu, Date datePublication, String statut) {
       this.employe = employe;
       this.tache = tache;
       this.contenu = contenu;
       this.datePublication = datePublication;
       this.statut = statut;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idtache_commentaire", unique=true, nullable=false)
    public Integer getIdtacheCommentaire() {
        return this.idtacheCommentaire;
    }
    
    public void setIdtacheCommentaire(Integer idtacheCommentaire) {
        this.idtacheCommentaire = idtacheCommentaire;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idemploye")
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idtache")
    public Tache getTache() {
        return this.tache;
    }
    
    public void setTache(Tache tache) {
        this.tache = tache;
    }

    
    @Column(name="contenu")
    public String getContenu() {
        return this.contenu;
    }
    
    public void setContenu(String contenu) {
        this.contenu = contenu;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_publication", length=19)
    public Date getDatePublication() {
        return this.datePublication;
    }
    
    public void setDatePublication(Date datePublication) {
        this.datePublication = datePublication;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }




}


