package net.keama.workspace.entity;
// Generated Feb 4, 2017 1:33:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name="utilisateur"
    ,catalog="workspace"
    , uniqueConstraints = @UniqueConstraint(columnNames="login") 
)
public class Utilisateur  implements java.io.Serializable {


     private Integer idutilisateur;
     private Employe employe;
     private ProfilUtilisateur profilUtilisateur;
     private String login;
     private String passe;
     private Date dateCreation;
     private String statut;
     private Set<Entreprise> entreprises = new HashSet<Entreprise>(0);

    public Utilisateur() {
    }

	
    public Utilisateur(ProfilUtilisateur profilUtilisateur, String login, String passe) {
        this.profilUtilisateur = profilUtilisateur;
        this.login = login;
        this.passe = passe;
    }
    public Utilisateur(Employe employe, ProfilUtilisateur profilUtilisateur, String login, String passe, Date dateCreation, String statut, Set<Entreprise> entreprises) {
       this.employe = employe;
       this.profilUtilisateur = profilUtilisateur;
       this.login = login;
       this.passe = passe;
       this.dateCreation = dateCreation;
       this.statut = statut;
       this.entreprises = entreprises;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idutilisateur", unique=true, nullable=false)
    public Integer getIdutilisateur() {
        return this.idutilisateur;
    }
    
    public void setIdutilisateur(Integer idutilisateur) {
        this.idutilisateur = idutilisateur;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idemploye")
    public Employe getEmploye() {
        return this.employe;
    }
    
    public void setEmploye(Employe employe) {
        this.employe = employe;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idprofil_utilisateur", nullable=false)
    public ProfilUtilisateur getProfilUtilisateur() {
        return this.profilUtilisateur;
    }
    
    public void setProfilUtilisateur(ProfilUtilisateur profilUtilisateur) {
        this.profilUtilisateur = profilUtilisateur;
    }

    
    @Column(name="login", unique=true, nullable=false, length=45)
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }

    
    @Column(name="passe", nullable=false, length=45)
    public String getPasse() {
        return this.passe;
    }
    
    public void setPasse(String passe) {
        this.passe = passe;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="date_creation", length=19)
    public Date getDateCreation() {
        return this.dateCreation;
    }
    
    public void setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }

    
    @Column(name="statut", length=45)
    public String getStatut() {
        return this.statut;
    }
    
    public void setStatut(String statut) {
        this.statut = statut;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="utilisateur")
    public Set<Entreprise> getEntreprises() {
        return this.entreprises;
    }
    
    public void setEntreprises(Set<Entreprise> entreprises) {
        this.entreprises = entreprises;
    }




}


